[window]
padding = { x = 5, y = 5}
opacity = 0.9

[font]
normal = { family = "HackNerdFont" }
bold = { family = "HackNerdFont" }
italic = { family = "HackNerdFont" }

size = 10

[selection]
save_to_clipboard = true

