import os

#terminal = 'kitty'
terminal = 'alacritty'
browser = 'google-chrome-stable'
file_manager = 'thunar'
rofi = 'rofi -show run'
lockscreen = 'betterlockscreen -l'
redshift_on = 'redshift -O 2800k'
redshift_off = 'redshift -x'
screenshot = 'scrot'
screenshot_manual = 'scrot -s'
volume_up = 'pactl set-sink-volume 0 +5%'
volume_down = 'pactl set-sink-volume 0 -5%'
volume_mute = 'pactl set-sink-mute 0 toggle'
light_up = 'brightnessctl set +10%'
light_down = 'brightnessctl set 10%-'
todo = 'kitty --detach nvim /home/markoso17/SB/ToDo.md'
